[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "7b175127a68e66648ea2eea049081ffab63e56a9"
os = "macos"

    [[nghttp2.download]]
    sha256 = "98a3b594fa1bd5aa9928e5530b157db0d8d7f9b1fc1ac0ca4bc07000c0b3031c"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+0/nghttp2.v1.41.0.aarch64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "57948cf597e3caa03318b660a8a7ace64ee45029"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "cd34dfc6566a32c3d021afd912a48aa7efe9c6598bbd3299f61e3b4369099dc8"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+0/nghttp2.v1.41.0.aarch64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "36a9f55364468c2754425bfc1e1ff43d3b1abaed"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "8540fc5fd14d3eed530e76b843bd89a68efc41f56695ba860f8b6ba43a6ec6ba"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+0/nghttp2.v1.41.0.aarch64-linux-musl.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "658e18f62968f2c7cda28f1865842646a5f23fe6"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "68a4a8d9c88d49df90366e9ba197e64a4ef3043d3a08129aaafaa9865023cde4"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+0/nghttp2.v1.41.0.armv6l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7ac9c507cb98beac70c0e2dbdf2d494e610f8e7c"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "5af87c7366701c2b77de29b3e0e49bc38cdb3ec80852f7490f2c4102f75cc2bb"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+0/nghttp2.v1.41.0.armv6l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "77f9c7888cde07ddd68c02eaa86cf11e9a95b08d"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "7e6ee269d286790d5f73395fc2d6f4dac468a0b6ee0d441ea6c9a3b3e5ed6d2d"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+0/nghttp2.v1.41.0.armv7l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "48b3615ccd593c696a7f3bb4b1fcf73c9e08bf64"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "922bfa329f513961e4f275ece8ccccb5012b544d3667e8141c51c336a46f274e"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+0/nghttp2.v1.41.0.armv7l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "4f81d162f36e37deeb93883d9b43ffcb7e919eb0"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "920ee3810383e52786c8116d93906d755363d67451514f592d6f039fe3b780a6"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+0/nghttp2.v1.41.0.i686-linux-gnu.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "b76224bce381179bc811a323b9257f2b115215bc"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "05064a5f718d8c72c47270b71650b7eb1f47dd4536ccacab19ea9083885b6511"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+0/nghttp2.v1.41.0.i686-linux-musl.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "f0dd2ad3d11faaed8655816c995185ac96286523"
os = "windows"

    [[nghttp2.download]]
    sha256 = "22b7e07997e2bd85afcf51137bb6dda3ebb598a3ad43d5663139e95d60bc7616"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+0/nghttp2.v1.41.0.i686-w64-mingw32.tar.gz"
[[nghttp2]]
arch = "powerpc64le"
git-tree-sha1 = "4c241fa4f8ab2ef9d7f5aa7bc0afc304d4f3092c"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "03e6cd7f0c5212d34b83b71e39724a3dbbcdf85a6ad3a05858881dfd1e11de0e"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+0/nghttp2.v1.41.0.powerpc64le-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "b59e5291f8154495fbd611f48cb2fc439f12b5ce"
os = "macos"

    [[nghttp2.download]]
    sha256 = "111725201d166580ac57ab87cb13a010db5ed89c1c5836d51dd00c41dc8cb28e"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+0/nghttp2.v1.41.0.x86_64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "1ce062048ba15a76f20d73ced5064b601b450cae"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "8ffdb08ab2704c8c92e7f8b56d6a59e16928bcd1c26796dca46b4c7552c5c2f8"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+0/nghttp2.v1.41.0.x86_64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "d32c5af809dc239255656bfe1a8260c121d6f281"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "1893771148d6a34f76725368e57acf6e8805ac3e7a3e778a6388aa86de16370b"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+0/nghttp2.v1.41.0.x86_64-linux-musl.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "959bfc289fa5a69a8190d0a9c2ba322263e871e9"
os = "freebsd"

    [[nghttp2.download]]
    sha256 = "513f0ceeb643025c246a5fc4e86179f4866619e202e80b172ebae5fdd6574e75"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+0/nghttp2.v1.41.0.x86_64-unknown-freebsd.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "0ee393a983bc100357c33aa2986fd8e0e817fff3"
os = "windows"

    [[nghttp2.download]]
    sha256 = "141897d42c50acc502fd8bd074439f7e1910a44a386a4083f31f9f466c2d2617"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+0/nghttp2.v1.41.0.x86_64-w64-mingw32.tar.gz"
