[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "298ff56a581459e2b80b8aa366674afc3c7315df"
os = "macos"

    [[nghttp2.download]]
    sha256 = "c9dd1d1268b106ab1a2912b6cd285a19bde0bdb95bdc78899e3f332d860b2977"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.61.0+0/nghttp2.v1.61.0.aarch64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "5e7a516aff295415638ae0fc1e579eefd5efadc8"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "b743f1bdd126245e5d3c2329e89aba5b6e8a3a4a746ba165fef7562a524e610d"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.61.0+0/nghttp2.v1.61.0.aarch64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "b78175aa0250971bf52fba5286cb2daa288d0133"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "fa3224a158d3ec84c368d0e7f229ebe620c45b71cf9f73c620f32d90f656ddc6"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.61.0+0/nghttp2.v1.61.0.aarch64-linux-musl.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0c0fb67428612a79b8ae799074c66515b370f46e"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "919f7c32590c4958edff740e4bae9bda56a827f01fa25702da078188d55799c2"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.61.0+0/nghttp2.v1.61.0.armv6l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ec1c9c4ed85dd925a938ba0d80fb5b437103aaf1"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "d51ec81a8289bc98c6bcd2d6196dc2ee2e0c5831fbba9a88e1f7bb9657166752"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.61.0+0/nghttp2.v1.61.0.armv6l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b6ce0998eac62043f9a48bb3fa5cf9f401b36b73"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "4ebc118b4f1bb606168ba6220289a6a5d8788591d48e0b7a846b859ef2bf97a3"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.61.0+0/nghttp2.v1.61.0.armv7l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3afa3e458504e0e180063f9fd3ef7e2e06f89c09"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "878c6d974bbf887dfa12cd4a77917dcba4f3e83c1e7ba6452ab14aedd4ee9d66"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.61.0+0/nghttp2.v1.61.0.armv7l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "cd5c50f7efa5e60c8d9d9e4a74a6862117ae9b56"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "10322011ae8344838b13dadef6f6ae0157384680619cf41c8240e2bbc3e01b80"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.61.0+0/nghttp2.v1.61.0.i686-linux-gnu.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "e628fcd394fd8418165b3c84d91abfb8491c37d1"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "1dda947ea1d0b7b8e4cc0508153e963bff29ca1a4dd2cb14ae6c65ba05cb3b8b"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.61.0+0/nghttp2.v1.61.0.i686-linux-musl.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "48abd858e64234f90483aec92b34878bfc931434"
os = "windows"

    [[nghttp2.download]]
    sha256 = "1da232907d5fa3f10ef8e847d63dc8c2c9b0c9bcb85086db6d7541e0837dcaa7"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.61.0+0/nghttp2.v1.61.0.i686-w64-mingw32.tar.gz"
[[nghttp2]]
arch = "powerpc64le"
git-tree-sha1 = "9789930de4c84114a7af137beb1b611fa21ac0cb"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "8c3fdf10e7d2b3c970782918eb83cc893ce27f415f20cd21459c7a924eaa3919"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.61.0+0/nghttp2.v1.61.0.powerpc64le-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "5275b09c73abd283b66cb7c7943ed8b4fbc0b671"
os = "macos"

    [[nghttp2.download]]
    sha256 = "e5d420b404be36d54b1303381c8bbf0db3e92d0e8c7142dbce1c58476326b36a"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.61.0+0/nghttp2.v1.61.0.x86_64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "7e6e2134cee1a1055046492c05232c972c6322a8"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "9d5da1030498f66ffc2128c0d5eb9d814c3e41127c49273e421df9e5ec827fef"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.61.0+0/nghttp2.v1.61.0.x86_64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "757589aadbae7a6798568d61848c3687edc2d271"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[nghttp2.download]]
    sha256 = "4e5418750e41762bb0dfa845f9597fe39f6a0b88030af733db3d1087b360ca6d"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.61.0+0/nghttp2.v1.61.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "77d9a18d68bd0391ff5c88b837805c145c4d7375"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "96a56910452a2656d80d689417fbbfc97a562974726b5a35aa29e4ccbcfd3899"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.61.0+0/nghttp2.v1.61.0.x86_64-linux-musl.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "dec316405789a6cac42cec2e757a676c444eafb1"
os = "freebsd"

    [[nghttp2.download]]
    sha256 = "aa882872bb5b19935bed56e51f53d81c10c537b8863c2c475f1e7108c0957513"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.61.0+0/nghttp2.v1.61.0.x86_64-unknown-freebsd.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "dbdbcc64ca534f6823c43cb28ae62e61835f8bd5"
os = "windows"

    [[nghttp2.download]]
    sha256 = "8227bf18b48f3d85ec50428aeb5e4a6f80026390a42dcbea50a863fd7fb543e4"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.61.0+0/nghttp2.v1.61.0.x86_64-w64-mingw32.tar.gz"
