[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "cecd70ccb0ebb3661bd490a0943ebc29481c126e"
os = "macos"

    [[nghttp2.download]]
    sha256 = "943dd0011103dd629c5e81ee9369e926a29af39db9032f05be61dcf855beb17b"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.69.0+0/nghttp2.v1.69.0.aarch64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "2abe2c0197328e509524f01ab2c2edd9ff93bb64"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "47676d3adc532522cc4b030c45e487f523522ab28a1dedabe22ba4f57cd48a4d"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.69.0+0/nghttp2.v1.69.0.aarch64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "46bf7713b7e03f447160c7722ac62babd7e63548"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "5a47eb495f77b8334e4e553a2e8665b531a8db1dac8f32adb6373a5237fd7e84"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.69.0+0/nghttp2.v1.69.0.aarch64-linux-musl.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "a0ee84066887ec4033478dbcb920f3746b31fc41"
os = "freebsd"

    [[nghttp2.download]]
    sha256 = "86586f08a48f7aac0013d51828610fe9fe43c29aa4bc553625163cf117e8acc9"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.69.0+0/nghttp2.v1.69.0.aarch64-unknown-freebsd.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e57a0055dce6c05e445dc2238cc9e380f95e6e15"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "5a8b1cedb56dd7e66953a7633695c3a7e5bf67f4c518bb8457196815f0b1f708"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.69.0+0/nghttp2.v1.69.0.armv6l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "be30ce7efb63dee628bedf14ad49e8575122496a"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "53531fa97129e9e7cd1cbe91c73156b237163c7226611b958b8d79a35e7d1505"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.69.0+0/nghttp2.v1.69.0.armv6l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ad3e17fe2a96b6a653deb02a465e0f6f178b620c"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "10cc7ccf76dcd19e3a6bb9f2088526a4e5e4e61057c3ac623e0e972a6dc92c7b"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.69.0+0/nghttp2.v1.69.0.armv7l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a021a281d1e9b431f5d148e5fd7024e1fa1b0c20"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "d630d05a1c17dfc94617e82b6d7f614362ec7d1d78131b7d91b71c5281676b4f"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.69.0+0/nghttp2.v1.69.0.armv7l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "1c27fea4d0a724bf3e8ea5c515e04b6cc95ff165"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "21b80c14b682a2708188a7eb3ed9f62807b97c80ae8c208f2fe79402ffb90ac8"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.69.0+0/nghttp2.v1.69.0.i686-linux-gnu.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "3c244b16c43d6c462caf54cb95eefd8dfe35d714"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "dda470f0b37ed40c6084bb3688aaca4a1df9936c1e8d1a10b4a6b9d7b12a315c"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.69.0+0/nghttp2.v1.69.0.i686-linux-musl.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "c427ddd7dd35d076a9ce5b914daf6d25b4434bb6"
os = "windows"

    [[nghttp2.download]]
    sha256 = "3bf1550b1c073e936a79c53357711ca1aefedc11b4c7d259865b335225c28e86"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.69.0+0/nghttp2.v1.69.0.i686-w64-mingw32.tar.gz"
[[nghttp2]]
arch = "powerpc64le"
git-tree-sha1 = "daa082121f744b932c7abef26ec3aca939af97f2"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "4b444ac396fffc07e9cd25f5e8a65f30e39d21770531335dada8a0e6c2b5ce50"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.69.0+0/nghttp2.v1.69.0.powerpc64le-linux-gnu.tar.gz"
[[nghttp2]]
arch = "riscv64"
git-tree-sha1 = "f0bf84ee13509ff5fcce43e13f4eaaa8ca38cc3d"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "d4067d024a06e2b5763f977ea854122bba82c8e00fbc839b3af272874bc676e9"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.69.0+0/nghttp2.v1.69.0.riscv64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "bb1ff85db329cc4f9fb9ebf16a1d95d26ee17943"
os = "macos"

    [[nghttp2.download]]
    sha256 = "07e7d9e0e4b01455078ac0afd7652b9a0e3578a8cee2fcaa42269a550df10800"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.69.0+0/nghttp2.v1.69.0.x86_64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "b794ea33b603c77e1b1ef24c0d87b852f40d903f"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "c4a1089d6ebdf3851874fae6103bbeca63c5ef7ff9bc40ac88f96e3965603dfa"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.69.0+0/nghttp2.v1.69.0.x86_64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "0c0cfb636e4781ca1d22c1df561423904aef2095"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[nghttp2.download]]
    sha256 = "aa565be376b003ce834653cc9016504216c68b1cdf05c93d6303a47eb67d8e05"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.69.0+0/nghttp2.v1.69.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "4c7f3dcf043a910409882fc50f3850e0ff5577f5"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "2a462c0fa863a1c5c55df4ce3ccdf3b39e2dda663c5c6e6a8883ed834942c748"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.69.0+0/nghttp2.v1.69.0.x86_64-linux-musl.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "00be7de7d030e38fd9ecccc4ebf9fcdaef544baf"
os = "freebsd"

    [[nghttp2.download]]
    sha256 = "328ff3849baf2bb325547c8812e050653285bf201ec61c7af0bc062a9d95b047"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.69.0+0/nghttp2.v1.69.0.x86_64-unknown-freebsd.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "6a18087a5e2f0fe7438bdb7a6cbafeadc05b259c"
os = "windows"

    [[nghttp2.download]]
    sha256 = "27dfbfb3ac35205bbaf7ae0ca35ea68010e8373896c4724dc0f03813d6dd04bf"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.69.0+0/nghttp2.v1.69.0.x86_64-w64-mingw32.tar.gz"
