[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "85364fc04157bb15dafd3f53a3d0a9084a8e15ec"
os = "macos"

    [[nghttp2.download]]
    sha256 = "ab9163c9a96c5bf170dff3dcec8a9bf5622e8f8735bad33b54f2a3fc19f883a4"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.1+0/nghttp2.v1.62.1.aarch64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "7e93fcdb3b7669750164feab18957a2082bc1aa7"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "909f584875811cb0ab41f62053874850d3f2df3dac7c345f3c01c6f8a27e4242"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.1+0/nghttp2.v1.62.1.aarch64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "38902f806f37acf60d0926cdedff84a7f7d1ce11"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "7827812bc87a0258eb9b1997ead2097937f814189d4f6713302724b20c8e848d"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.1+0/nghttp2.v1.62.1.aarch64-linux-musl.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1745d8586106781fb21f8f6411e2e7576748588c"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "995d9c568f1ef89877ae4946ec567090313a272134117d8d09acf73183edb368"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.1+0/nghttp2.v1.62.1.armv6l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "82cb2f69155e9dd58bb9fade073f762cc57ad145"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "f8967762202bed32500b8c90174ac0b47b0dba5f8f9cca460414a7b2b1182dbc"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.1+0/nghttp2.v1.62.1.armv6l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ed01a22c672253ab832e95de75738db8b945609a"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "ce9332ea8b20803ec89899b9feaabdabc169d528a892c9d773fe4f1aa100e027"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.1+0/nghttp2.v1.62.1.armv7l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "686ad6753d3c7a5ddbbd603ae7980f1a4a0f77cd"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "cf2a49a8bdf8258b2b154d1f54b48975154f3de5d47f9321be1482dff9f517ec"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.1+0/nghttp2.v1.62.1.armv7l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "9a53e72e8c743406651ccad82758f7786367b72d"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "141b814229b8fae2129e2fed9e9745c793cefdebd67213f651f052e9183f85be"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.1+0/nghttp2.v1.62.1.i686-linux-gnu.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "d9f679f7704775354dfbc2fb5e2f8d3fb56c945c"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "38ba1bdaf89355b6e8c150596949426c7dc64ead4bc6243f78339e4b2240a2f3"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.1+0/nghttp2.v1.62.1.i686-linux-musl.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "d71caaf46daaebff063394e606bab46b653311a8"
os = "windows"

    [[nghttp2.download]]
    sha256 = "bb00d87a4ac64a95a4ce47a57bceb8c62e71f8f64cab853394d32621e494124a"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.1+0/nghttp2.v1.62.1.i686-w64-mingw32.tar.gz"
[[nghttp2]]
arch = "powerpc64le"
git-tree-sha1 = "d01cc915ef48e0790cc1ff2bc55b4e84fe17d7c0"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "cf8c89e977d0bed22fca12b63cf6a03ba0ce8debc7ca9b973c21ffd9a5628972"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.1+0/nghttp2.v1.62.1.powerpc64le-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "2fd4d6795af35bfea622253d1963e0fc59ba394c"
os = "macos"

    [[nghttp2.download]]
    sha256 = "33f74e10fc3776f4e14c3af7cce6ce3a6852d7c20ad9f51e6c432fbac6ec0e07"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.1+0/nghttp2.v1.62.1.x86_64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "aa38be4349e804e7a348711d0766c579dcea4f03"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "157a475d94fb331d9340bbc707409fbc8a703bd447ff86fb224282c53602a083"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.1+0/nghttp2.v1.62.1.x86_64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "14d07d62b8559f6bb0531956580f112f7f80bf7d"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[nghttp2.download]]
    sha256 = "87fc1db973b7352cbcc6577d23bda44a7595c6f07752b15cb2c072a0a0e3880a"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.1+0/nghttp2.v1.62.1.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "feab1b3f9e94364d08551e3064ef886aa44eb58b"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "76e4e27213703917a2bc0a2f5a5ccf93da3996feddad045313f9d3555797172e"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.1+0/nghttp2.v1.62.1.x86_64-linux-musl.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "b54103365850a57fc222291073b92d26408faf5d"
os = "freebsd"

    [[nghttp2.download]]
    sha256 = "6823a8ddc092fb943716f1a0b98eb878eba1fe416bafd5c9411d7ccd53a0bea3"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.1+0/nghttp2.v1.62.1.x86_64-unknown-freebsd.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "261f58c001d751540e299844afe5c4cd4a369bad"
os = "windows"

    [[nghttp2.download]]
    sha256 = "8453a1c7b4f159f48863a37c45d6e626c95b05f89f4f2252e755588ec8054485"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.1+0/nghttp2.v1.62.1.x86_64-w64-mingw32.tar.gz"
