[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "95b1659a57ea5f41891c30b962e5687d407e5033"
os = "macos"

    [[nghttp2.download]]
    sha256 = "f37241d0a4092ffa3dbf6652c1f42a85ed2c3395eb0f2348cac5feb8948d361e"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.66.0+0/nghttp2.v1.66.0.aarch64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "d1775c54320c2d6ecd0e1caabcb09d98499b061b"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "359925c62d7bf6e6f31e9dfcd1f41c3f8c99874ade7f5c28ad279e817d5b6e94"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.66.0+0/nghttp2.v1.66.0.aarch64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "9033a186d74b6273d1df151d4dada10b91f7a900"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "32cb7c049b0ad414e08360a74b4fef8e1bd9f127d29968c7bc90449400599614"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.66.0+0/nghttp2.v1.66.0.aarch64-linux-musl.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "0e4340fb9b5577554c6158b8672dea9e641fd2d8"
os = "freebsd"

    [[nghttp2.download]]
    sha256 = "72d0d826bfd5df5b15c54c3b99935d8f6df63bfb963e16e7bc73f6523443eab4"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.66.0+0/nghttp2.v1.66.0.aarch64-unknown-freebsd.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c7e8bf776cd6e0ae2ff50fd25f9559558d83170c"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "0db62b38c734865899f9f56fe7afaf33cc18fa3cbeb74bafc7f2c1074c2853aa"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.66.0+0/nghttp2.v1.66.0.armv6l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8fe476860391f05a04b2cb9ae05db05d12397aae"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "75a995a3056df00287d36a3870e9680b7076ba657d040c4266bc7de5e4adb674"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.66.0+0/nghttp2.v1.66.0.armv6l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8c62e0edf7bee2ba2ca4b08492f05613549a3685"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "e47b89c96a500cd6bf4eb14fb62cac5f1755d819ecfbef52e6d3021ccb60f0f3"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.66.0+0/nghttp2.v1.66.0.armv7l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ffcb621d27f35bd0506b7db7258c4ed0bc4a8d4b"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "eb01d9b05264095e79a8208308756f473b62baacceac49e9674ef1261a1bfd27"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.66.0+0/nghttp2.v1.66.0.armv7l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "765663c6cd43ec89fcb1f42d1ea6146d1dce9de3"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "e70bb93826c006f48b11204acc791de9f7af9a680f4305fa0639862b6647f548"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.66.0+0/nghttp2.v1.66.0.i686-linux-gnu.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "338d9d34bfa87272c6eb9ce7d9a9bc3d6bb46812"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "7c8545e9dacee1981f355ed8917a762291475cc6a2c8e9cdf17d6782da0efd76"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.66.0+0/nghttp2.v1.66.0.i686-linux-musl.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "84e6ea2ac578956ef5eb697ac58efa689263e82c"
os = "windows"

    [[nghttp2.download]]
    sha256 = "49cdf519d36872f271d3503f85c100267e566691ec090e2e925b4d793a525272"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.66.0+0/nghttp2.v1.66.0.i686-w64-mingw32.tar.gz"
[[nghttp2]]
arch = "powerpc64le"
git-tree-sha1 = "97c6e972e239ea2e673a3342bbd3d369133842b4"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "bb491d6dbad67c53740b4e6234a049f9bb68da2c36c89b0ebe832f1c311f8d38"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.66.0+0/nghttp2.v1.66.0.powerpc64le-linux-gnu.tar.gz"
[[nghttp2]]
arch = "riscv64"
git-tree-sha1 = "c32864cc1b7545ccfa580821fe06a2ef0de25384"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "b52105a7f055e1af90be0df49a4218b6888019fbc42cd9f30c92e9f52d6d31b0"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.66.0+0/nghttp2.v1.66.0.riscv64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "81b0e73ae2c0bcb44378a198bf383bdc25343c3a"
os = "macos"

    [[nghttp2.download]]
    sha256 = "66ef750fb6406dd525ace3ec3acba4fca9b9dfb5031c9d1302cbc10b0312473c"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.66.0+0/nghttp2.v1.66.0.x86_64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "00ee7868058bff30b114422bdb2125f51922d832"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "1f312109999f0d8a350c89ef13143562826ad6104e0f8994d6f9de445e9e82a1"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.66.0+0/nghttp2.v1.66.0.x86_64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "ccfb4bb1cbebb42215f7f6a0ac53a971ad110607"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[nghttp2.download]]
    sha256 = "5f5ae8736189ae59165c554da31e73746d014717b33e1eb305b31a9159ac2840"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.66.0+0/nghttp2.v1.66.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "81bd2d518d7492e5abcc0f96fbd29dc398b9c64d"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "c84536fd4f23e487f12d7617fec7388e9112bb46859ebf192c7b694dd8eef707"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.66.0+0/nghttp2.v1.66.0.x86_64-linux-musl.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "7542552208c3adde720ff5ba8624afeb6d250e43"
os = "freebsd"

    [[nghttp2.download]]
    sha256 = "c5c099c4e75061663996fa6aa0901414558e4d07a1bd7bb5aae0ff27b98388a2"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.66.0+0/nghttp2.v1.66.0.x86_64-unknown-freebsd.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "f49e29fdbff99d66ec27a19fa4fd3699e58ae28e"
os = "windows"

    [[nghttp2.download]]
    sha256 = "b36a63e83e01ce6ff1dcd66208a0b777d8eaf782e49f7283c1e765f7536522b4"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.66.0+0/nghttp2.v1.66.0.x86_64-w64-mingw32.tar.gz"
