[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "bfa82829619c131b583770aaf37e0ca0256bd638"
os = "macos"

    [[nghttp2.download]]
    sha256 = "1b2f670fe30726d96ad39d352ec4d6f8835946f516a179726733c68ffd13c400"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.47.0+0/nghttp2.v1.47.0.aarch64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "a4df157c14b9c5fbb30a2ea181b9c52646c758e1"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "7f29454598cf790bf76fafa5ceca6273ecf7d4a547e8cad445df49dcf6efb0a6"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.47.0+0/nghttp2.v1.47.0.aarch64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "28ab5b8d55822409117aeee3d3f24c7d3822af17"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "e50ec16714df17e572c71e4f492d16e0ea2804337749d9feaec73f398dddd64e"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.47.0+0/nghttp2.v1.47.0.aarch64-linux-musl.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "92025a90ed11dc11aab8c38ba741728f53714302"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "23a3f01ad486d60031a8624329d7686f55cde3c792b799a5f9514e72c589327a"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.47.0+0/nghttp2.v1.47.0.armv6l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "69c59debaee44db6f99220fa8ed31097149efb5c"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "d0c7274cb215f9a83692b087f0c229514f83dff2d30e18af4d146fe349082ba1"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.47.0+0/nghttp2.v1.47.0.armv6l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "659dc867c15831ab5bc8f1be8055b8da752f7246"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "eb30ef842131ff2d1cac0e1e55a7e9309989fc7a52d5374be262bf522b274a53"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.47.0+0/nghttp2.v1.47.0.armv7l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "30e7be7d766d32967c4deb5bb5e53a9fe1bbba26"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "094bececdd4bf1e89c6d657d7e5469d272675e7c4702b275c0e0e52943403c9b"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.47.0+0/nghttp2.v1.47.0.armv7l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "3e24f6f87df30066e8f419a4bcd71e7231fe0ff8"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "d9fef01d91f5d8d6b5537e04f23150184c5950efee11eb668da1a405c316f728"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.47.0+0/nghttp2.v1.47.0.i686-linux-gnu.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "cdc85df89c7247a8b3a78863207aef8d213607e2"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "47f6d2e03715dfee89de3088b83c2961af9e68e444ec5230e11762e12a12f3c8"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.47.0+0/nghttp2.v1.47.0.i686-linux-musl.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "fc322d35ac36c0c57f94a9d5458b10e5da325b70"
os = "windows"

    [[nghttp2.download]]
    sha256 = "136001b4985a02cf84a7d50f5467a09a8d29e79d24341b600110c2192f3b4d0b"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.47.0+0/nghttp2.v1.47.0.i686-w64-mingw32.tar.gz"
[[nghttp2]]
arch = "powerpc64le"
git-tree-sha1 = "a8e6c2308642b91572c2a9b6b423524b5485e31b"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "fc950c53bc5c9ca10f5f64ddf047a80fd027fd20ffcc7d08cc16bb76e58e5e50"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.47.0+0/nghttp2.v1.47.0.powerpc64le-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "32857b095d5924301bb86ead8a32579e4357f99a"
os = "macos"

    [[nghttp2.download]]
    sha256 = "5ee7bf5f4fcec01e957f54ededfe6df7e65839f23865c817c84fa78797f49717"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.47.0+0/nghttp2.v1.47.0.x86_64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "3e4c8b21e4289ef83065aed2c7d052b75736a75c"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "34cea8406da62ef1c6d64fe43ed603e696ffb67caee3752d9858388de9a5e8cc"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.47.0+0/nghttp2.v1.47.0.x86_64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "3d9a201350abdbc73b157c485e0fb617a00c21dc"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "3e7ac24235be1434a5d9a5f51387356a3d3698bab689882ed8e8d6805cf3d709"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.47.0+0/nghttp2.v1.47.0.x86_64-linux-musl.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "bb71ac301edcb5ab4bdf8526b8b6f463e1a259e9"
os = "freebsd"

    [[nghttp2.download]]
    sha256 = "99f83ba981222235ea795475f8cf42373be887806245ae15fef12e52c865cc4a"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.47.0+0/nghttp2.v1.47.0.x86_64-unknown-freebsd.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "30bdeb02c1f067118f1f0846c0a80809fe5445da"
os = "windows"

    [[nghttp2.download]]
    sha256 = "62fbfce3efc63835dbc586c989181e274634659292ea389f5ee104ffeae0f62d"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.47.0+0/nghttp2.v1.47.0.x86_64-w64-mingw32.tar.gz"
