[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "f8d4d1ebfee0f4e6c0bf1690acafdf10eec05e2e"
os = "macos"

    [[nghttp2.download]]
    sha256 = "90ffb7f755ea73f55ac8f698b9c5ced2ed5aa6a1d45ae0b939da68d0c83307a4"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.64.0+0/nghttp2.v1.64.0.aarch64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "c11214e45443c92b8ca4fee497272924c576db00"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "158ebd38453b532a34cc295430fdfffe438a52991dfb453f5368bba21ca650a9"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.64.0+0/nghttp2.v1.64.0.aarch64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "444cf6a3e84429206812c332a036feb8cd1e6d5d"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "ef27c792b69f44b06e54a4388fd1cbdb64bbeb5363b20e33b66ccf192aa6dae6"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.64.0+0/nghttp2.v1.64.0.aarch64-linux-musl.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "46b3346e85ad96061da9254c92edf32d498bae22"
os = "freebsd"

    [[nghttp2.download]]
    sha256 = "6bd8facfec604e6710a4876d8071cf0420468fd0a1fbc44cb8a753c984797bd7"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.64.0+0/nghttp2.v1.64.0.aarch64-unknown-freebsd.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "81743522d4bd946062008cd37acd6d7b47457dfa"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "a62dacffc546f4d4a78fd001816d151340d77469377ad1424d38e6393d3125db"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.64.0+0/nghttp2.v1.64.0.armv6l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b7a546d75d59d9cd2aa9dfdb220dbaa625d184c2"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "fb4afa0f1bdd78458cdc010ccb2e8a84a7fa4a4fa9526054bf673b513b217a01"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.64.0+0/nghttp2.v1.64.0.armv6l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d0997917512161a6f2134e7a3780e33ac9e62fee"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "4b392bc966683c14810306d5102e6479a9ed734a8dbe2b15a8498b4c74275c18"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.64.0+0/nghttp2.v1.64.0.armv7l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "261ead2b9252791f4833e89aec4f4bc04cf8b4f0"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "1e8326806f181a53985298727e24b82838563953170089ea54d5fa2ae33acf6b"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.64.0+0/nghttp2.v1.64.0.armv7l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "f2adff264e1eac2ad7452a25e6424ee2d8a6831c"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "59ee38ff9da188d578b9aa698d879f3c36d8e35dc20eb83f6acb1d068be0fd6a"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.64.0+0/nghttp2.v1.64.0.i686-linux-gnu.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "049f4e3dac60d3a4a72a9597444dfc6530ca35b9"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "c011968e139aa787d9317da71e9703cbae98a34b16b3ee629d7b3a188b0b791e"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.64.0+0/nghttp2.v1.64.0.i686-linux-musl.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "b26c9bfad6bed9043be9a32d2d81c2fcd96dd15e"
os = "windows"

    [[nghttp2.download]]
    sha256 = "9c3df0595a78f24115f0c340b0f0ab991508b46e7dbdee669d8a5fb21a106ffe"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.64.0+0/nghttp2.v1.64.0.i686-w64-mingw32.tar.gz"
[[nghttp2]]
arch = "powerpc64le"
git-tree-sha1 = "4197e2c494e774aff1fc4589b075f1326617b9a5"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "64a5bcec68cc19f0d4969443b3f09acb8525b07ea45d5b0ac122715e5a85ac99"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.64.0+0/nghttp2.v1.64.0.powerpc64le-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "7a6c5e74b4760afc8722fc6b0e363334a13da5f3"
os = "macos"

    [[nghttp2.download]]
    sha256 = "f62406b4c4bd4aa504f78ff00c2d2a5d9a767b6e14fe232ed8f17ee97de03c12"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.64.0+0/nghttp2.v1.64.0.x86_64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "ee0000c3a9e8fb4e99c5a346af8303e0b79e82a7"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "4b6bcbe6e5bb4d29a2288688ac5b2514048610bcad0a774f953451ab543fcfb8"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.64.0+0/nghttp2.v1.64.0.x86_64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "7d55dab46f239f5d553126f4e894d698bf1a78a2"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[nghttp2.download]]
    sha256 = "4feae754a4d033c5eb8aea468ec788d398a2e6568f7224b52079e1578816f72a"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.64.0+0/nghttp2.v1.64.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "a20a390b29239324474b50b7a1a581bf365c2487"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "d98f45797f63154231e2ea9e0d5751cb902a55ddcb7d62f8f5e02a896b57bb12"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.64.0+0/nghttp2.v1.64.0.x86_64-linux-musl.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "ba6d88c699f0044ef03a4658e7275f29b471c3c7"
os = "freebsd"

    [[nghttp2.download]]
    sha256 = "3714e3313c7e7129c55e987ea5221f255028dcd346198b0b5d744d687178a736"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.64.0+0/nghttp2.v1.64.0.x86_64-unknown-freebsd.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "736c20439f574f8e463308e6af15bd42e1f85755"
os = "windows"

    [[nghttp2.download]]
    sha256 = "79e8784ad17895966c2153efb35844ed08d5b01a94fe9329d26775e2781046ac"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.64.0+0/nghttp2.v1.64.0.x86_64-w64-mingw32.tar.gz"
