[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "9c16667a48d23ca1ec1e2d7ee962e3c73b786936"
os = "macos"

    [[nghttp2.download]]
    sha256 = "79b80e09f41ce996b4b92870174b128914cb5345c8cb4d1a4d55a703288b063c"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+2/nghttp2.v1.41.0.aarch64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "b58d3def36e6c6e75723f4e82a9ecd5ddf187306"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "38c796e239a7cec8f9a30113fc3aafa81195f02f8b8ba401dfe83df122cf7254"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+2/nghttp2.v1.41.0.aarch64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "cb05386769b56db294ce913334789bbeada31584"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "d40e9d0b10d9436a22052a78ff3cb04b930e6756ffe80597cfd5a1563b3d1571"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+2/nghttp2.v1.41.0.aarch64-linux-musl.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fd656d35b8f0ba3627cc426a3b3c47d141787bc2"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "cf7e7fe24adbcdaa9e647bf29b997f5dc19cf358dc0e0d49f08b0b7f3fd473d2"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+2/nghttp2.v1.41.0.armv6l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "688c24ba8519343699b064a60d5651e67b845a4e"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "d68ab60168735c61348f8704d5436d4a551068769be76d384d7b3cf96b78d8c8"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+2/nghttp2.v1.41.0.armv6l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "92074482e05bcce02c3947f796ce353079dfd91a"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "5837a90f78ba1a45a55f9925789717180b87c8190a652931c9a1140ec125bb5a"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+2/nghttp2.v1.41.0.armv7l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6e39f02e69fed071008e8b8bc7c7d4fdd697596f"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "fcc19414d38ac1913f11955749829ca0a08de28078d22b9c8938cb7f604c7931"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+2/nghttp2.v1.41.0.armv7l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "fa911695ddfc78ca151cff95573bada7331ca6a4"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "1772db0411d9f73fb770b9b17434f3be95fcbfa192391b447b92f450cfe84402"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+2/nghttp2.v1.41.0.i686-linux-gnu.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "114a1822350bff3d890cac8ab88bd6858bb76d09"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "a7bff0672c9f65f802b6d0a602f646b04314e7ca09d12a9dfb0380171bca9869"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+2/nghttp2.v1.41.0.i686-linux-musl.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "2450d22492e485cd5c16dea0a56e095c698b3679"
os = "windows"

    [[nghttp2.download]]
    sha256 = "3237bc329ca9ab1a23665b69a1948c7d87d295f26e90d1673a09af4b3a9a85ec"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+2/nghttp2.v1.41.0.i686-w64-mingw32.tar.gz"
[[nghttp2]]
arch = "powerpc64le"
git-tree-sha1 = "5fdbf7a17b2f17f3b2d27944b5e48fcd48dd907d"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "8233e6a6fcd81bff743ce46de71e5a9512283e0c5cf4ae7c20bc3334a3514400"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+2/nghttp2.v1.41.0.powerpc64le-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "ed04e1634179c3fe0fc9ac3572b846b8a7faa494"
os = "macos"

    [[nghttp2.download]]
    sha256 = "f28fbe0c9af27c7e17a1e483e5751505892581dd712ae557f6ab730403481179"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+2/nghttp2.v1.41.0.x86_64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "11895391e48dceefb2ec10a145d778e19ee0114c"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "c0d66af0f20d2aa23a3f2daddbd820cd7d568c76ec9e7f3ce01a411fc91c0f63"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+2/nghttp2.v1.41.0.x86_64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "52fefb302424067c48f1c472215f3d9471ebc5ba"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "66d3582108078615ac26b62e697499cdcaa547f60e7b3ee1564dbc9901f662dd"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+2/nghttp2.v1.41.0.x86_64-linux-musl.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "022e887d2ed9efa130b590c1a122be196f4566fb"
os = "freebsd"

    [[nghttp2.download]]
    sha256 = "07690424eccc4bb2556769d747959fee764b5bbe24d91b02a36e7b87929751e8"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+2/nghttp2.v1.41.0.x86_64-unknown-freebsd.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "ff5ce045ebf252091e56056de392f43d3781364c"
os = "windows"

    [[nghttp2.download]]
    sha256 = "3f7094d546bd7e07f0f8bdabb59653a554416a6631aa58c0b0228e718cc6a214"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+2/nghttp2.v1.41.0.x86_64-w64-mingw32.tar.gz"
