[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "0b65f1af4c4b57b63585fca76acf87a36da4ee61"
os = "macos"

    [[nghttp2.download]]
    sha256 = "1cd5ea2af9a9ffc8618a1fa7a1a816abae4da87d38441d7512cc436036de0502"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.68.0+1/nghttp2.v1.68.0.aarch64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "176310ec457d2537d25122d7eb2c267230e1d7de"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "df4c90a8cd5635503dd72c42f21cbe648abbeeda24c4c336fb0af43ff3fa1a76"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.68.0+1/nghttp2.v1.68.0.aarch64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "ad7747a51f77807edcc639e974c092afe7e7271e"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "cd87884e4e94e0763bd439ba21230e09795fc5c58a0e60e572d83390bd885273"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.68.0+1/nghttp2.v1.68.0.aarch64-linux-musl.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "2ecd595b4955b19bd0325ed1c4c73a8ec913aaa2"
os = "freebsd"

    [[nghttp2.download]]
    sha256 = "b43fc8e10c42e66a7d92f3b4e8bb571462295a07ddc371371426f14f149dfcfd"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.68.0+1/nghttp2.v1.68.0.aarch64-unknown-freebsd.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d10bf80a4aeabd6b72b2de928b20c878ac01c56a"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "356bb0a14343dc92dc087e705499245049b9049070ec2321f6daaa1b46e1aaaa"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.68.0+1/nghttp2.v1.68.0.armv6l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "af409d948946c6f28cbe0dccb15035dd2383c9f4"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "fb4f74fe0ad1e4c6c18673ffdb79418823f47ab0e829d5278451dc195ccd02f1"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.68.0+1/nghttp2.v1.68.0.armv6l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8982785d1b35b6178102aca47e1778ee94a361f9"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "60d0da68653ce02d1caa629db24451cbdf8cff857870d18c6b5956ccf26aa94d"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.68.0+1/nghttp2.v1.68.0.armv7l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5c7311ace1271102d984b9d4548d08de63acd8c5"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "26059d53520ef9ec3928fbdcaee6fae3fc074b8dcd4173988341ebd80e463c18"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.68.0+1/nghttp2.v1.68.0.armv7l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "2abcfe78db4f8177a605fe5a7a8f33173b0c44d2"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "6b4940393e5a9d13837ef35ef57b9718a4601a1efce7cbd87d47883e58a15202"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.68.0+1/nghttp2.v1.68.0.i686-linux-gnu.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "92f9da4475ffda4298613a3f048b40f842a8794c"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "9baf7022ab1507f134abd2c14ec29ee72f5a509b9fd5c0ca470d3ae7a3ca6bdf"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.68.0+1/nghttp2.v1.68.0.i686-linux-musl.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "73539c4635eb61f9fca1f1927cd6975efd6f228d"
os = "windows"

    [[nghttp2.download]]
    sha256 = "2624af50a8f381ccb2ec536348ca2705b28a10f73780938d140c24316f073940"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.68.0+1/nghttp2.v1.68.0.i686-w64-mingw32.tar.gz"
[[nghttp2]]
arch = "powerpc64le"
git-tree-sha1 = "f0e4aa010f58d9c6b8be3e7813d00ebb0d710812"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "cbdd75b009462e34a053660640dc44789efcfefbe2cf466d8568b2427fd75e26"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.68.0+1/nghttp2.v1.68.0.powerpc64le-linux-gnu.tar.gz"
[[nghttp2]]
arch = "riscv64"
git-tree-sha1 = "5512bb40ed8693a247baff96602d8084b17f1bd8"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "bffea41681a7abac9b30ef8e4c493b89cde432689e5380d3547691a2a8be572e"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.68.0+1/nghttp2.v1.68.0.riscv64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "97291206bbbe90ee69781adad07bddb397a51167"
os = "macos"

    [[nghttp2.download]]
    sha256 = "0451bc9b34077dd82270fadace9e727917a86fb5f8a94fe611e9e290c111da79"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.68.0+1/nghttp2.v1.68.0.x86_64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "1004ab6f806c2eaad58fa1168aef0830ba69f723"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "54f58386bf0c51036642214928170802480eb7bab03f31cbe13d0de4015422bd"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.68.0+1/nghttp2.v1.68.0.x86_64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "40e760bccac7c98a82ef157249127ce85b55e4ed"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[nghttp2.download]]
    sha256 = "de5948e2119dcacb6d0a133562401c4de1d637309fac532b582de893f72a6340"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.68.0+1/nghttp2.v1.68.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "4f18dc273f118d947502f90fd83287982cc9683f"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "8f4ed022c7e980f5be0b82c372a504d6aecff5fcb0a7d69a7414b3c7adbe02e8"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.68.0+1/nghttp2.v1.68.0.x86_64-linux-musl.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "56d1463756fb4a4c25ae574cf3e498d0541b19e5"
os = "freebsd"

    [[nghttp2.download]]
    sha256 = "5bc1ac3e05a500101da2753918f2bedb3052075d6c71796616357ef904c93914"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.68.0+1/nghttp2.v1.68.0.x86_64-unknown-freebsd.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "21c31a64b432e02023b21a7d066484a64c4ac658"
os = "windows"

    [[nghttp2.download]]
    sha256 = "c8480d1ee42f92748165c92f55e5de4feab5fda7861e56bb064bb7eda06ac10e"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.68.0+1/nghttp2.v1.68.0.x86_64-w64-mingw32.tar.gz"
