[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "38a5a2f155a428efe79fc6d626f791a664f2a335"
os = "macos"

    [[nghttp2.download]]
    sha256 = "4b897a9430b1b7b7828426ce6f8c3dc9326d38650886000f834cc69d71e49e3f"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.48.0+1/nghttp2.v1.48.0.aarch64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "0776c1d1844a4e2e2cca0e6751a40f285938dd39"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "6285e2b1d4c86ac9cce0bae7b4a58455516d3f17501a05ebeebc581cffb3be3f"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.48.0+1/nghttp2.v1.48.0.aarch64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "4708a6901f59dca3899eb16bc0329dc538d74e3b"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "a2ad45eb5d55bafe5d4488b36a3ef291c808db3e3590d9ed49320b2e1bc1fc21"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.48.0+1/nghttp2.v1.48.0.aarch64-linux-musl.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "59b377698f88278663358c86946eb45cdbb72b2c"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "76663f51b14402171a1f74b27377fb2893f61ff359daff06fc332b928302b1d2"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.48.0+1/nghttp2.v1.48.0.armv6l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8ca9b3173f4556b275d7224eb53553301b8ca66e"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "2dd9e8ef61c0a4b907073bb0a471da280bcc7a42f5c79fe1f7be1b7c27f50490"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.48.0+1/nghttp2.v1.48.0.armv6l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cc2fe87c2200260b003dca5914fdbc02e06c0495"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "b6ca5f69b400a6972f33aa06054ff653af8e23ec9e25b04733b8fbb521f9a6a2"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.48.0+1/nghttp2.v1.48.0.armv7l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c60d8f6ca5a2656bffaf6cc23427f932db1cb786"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "01e8b5f057bee19572dac9a195452b437f8057e25b733515ad0bd31045fbaed4"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.48.0+1/nghttp2.v1.48.0.armv7l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "38208a87aed8ce913a825ff646674277db1dfa69"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "75cc492f7bd8685b35af08a81bb66486ca37372b9af9ee1ea973729b43ef3583"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.48.0+1/nghttp2.v1.48.0.i686-linux-gnu.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "9cf45de0cc2399edf0ba53769c0e83f357d78a16"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "0f80e8ea92de25ab88732480f13c7eeaad6606e77aab99d1706cdd580b2bc482"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.48.0+1/nghttp2.v1.48.0.i686-linux-musl.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "2cd2eeec8e8f8f37437d26ec8b326dc3ccf692ae"
os = "windows"

    [[nghttp2.download]]
    sha256 = "881829c8d6ff7c569367d54fd3761270249ed59ee8d4af1322cc9c0cc3767888"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.48.0+1/nghttp2.v1.48.0.i686-w64-mingw32.tar.gz"
[[nghttp2]]
arch = "powerpc64le"
git-tree-sha1 = "bf884ec8463bc8f4e539f2faf0f5c8ba5a4b2558"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "089c294aed96bb70f14e8e43e44cdb1cbf6964c32874dc28e459bfbc26ddcf7e"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.48.0+1/nghttp2.v1.48.0.powerpc64le-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "44d74438672a3fd0e5b579d6dd69cd3862fd37c3"
os = "macos"

    [[nghttp2.download]]
    sha256 = "884342d5519738f49b714bfc98ce5eeaaa92207d54a8a399f1608241bf027686"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.48.0+1/nghttp2.v1.48.0.x86_64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "90536378d6b1742f5d6fcc2e002bbf2651f456e1"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "c9ad831396843ecc622264badd368078679906cd17bcc5f1d9c1a6d41b915c05"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.48.0+1/nghttp2.v1.48.0.x86_64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "05832c9ee120aa5bba74b0f4ebaf65e3f6fec7fb"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[nghttp2.download]]
    sha256 = "2880ac05af5efd7a1559ba550878793603a1d8f4619e56d5e29eefef1dd11d2a"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.48.0+1/nghttp2.v1.48.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "9e6c3fc9f7f0c365ecedfbffc022addd64d18248"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "b4fb96797b8f635dc15995fb617b63570ffb627e3479105f2b0ac6302219c333"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.48.0+1/nghttp2.v1.48.0.x86_64-linux-musl.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "ef10d5aaba9069f19e18f179fcf5f3f90e368a1a"
os = "freebsd"

    [[nghttp2.download]]
    sha256 = "f6d111672ae0b50185161328d0d0240ad52c37f7127693bea28619b7e28f2c54"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.48.0+1/nghttp2.v1.48.0.x86_64-unknown-freebsd.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "f02e77f65281a7e1cbcf7e08de46aa8ad78d2efc"
os = "windows"

    [[nghttp2.download]]
    sha256 = "47bf7b8889f179ebea638511717e759884d988e23d01114516f86f593fa5e7ec"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.48.0+1/nghttp2.v1.48.0.x86_64-w64-mingw32.tar.gz"
