[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "c699b80506ddf3f3b313ac030fee4ca181543d20"
os = "macos"

    [[nghttp2.download]]
    sha256 = "354a6ebd38f25ae29c96d571fb1bd472852b8c82b556e7f4d2318273b632270d"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.60.0+0/nghttp2.v1.60.0.aarch64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "d0b0d17614e1629ab3c26a66aa59843131ca3b8c"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "9464d0d16ff00b2e8e916541c75feedaab20456c6f88580b841c7bb5c1a002b0"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.60.0+0/nghttp2.v1.60.0.aarch64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "acd594d798fb5d761c389aaa57d3fea1649e64d6"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "51d71744032c382096a9314790d2e069c17e4d1b087a29e535394ffcd81d6155"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.60.0+0/nghttp2.v1.60.0.aarch64-linux-musl.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e2c6d199761e24c58263aae4afca817c5918fe2e"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "0bf479af5b6e8d681aeb7c97790610eb39dd3ced81755266cb5db6e6f1717c89"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.60.0+0/nghttp2.v1.60.0.armv6l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "57a87e7059d9eae93655f65acc162e4dcf89e0e4"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "e10ab81ed181239221b8d478076cbeb80d8009c851eb07ef5857e4bbac66b28d"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.60.0+0/nghttp2.v1.60.0.armv6l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5cbf72dad303f4f1ad683304e9af92756b9947e6"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "211b344875dd41fe09994328bbe57fc7b9f15b9fea3614e1f48c0db10ca92247"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.60.0+0/nghttp2.v1.60.0.armv7l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "11ab9703a914e62b794c7310c1fbb5595b457929"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "a18b20da1d96da2740b422f9579f88dd82a27d8aa9cdb2889650eff7f0d7f8b1"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.60.0+0/nghttp2.v1.60.0.armv7l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "82e0d646d040d73f2815f44c1bb2507b784bf376"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "6417b755e3c0030ebfb233064bcd7b2a3e239036001a44dcf2340553a34a7acc"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.60.0+0/nghttp2.v1.60.0.i686-linux-gnu.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "6cc39401aaafbabe20c0e8b88a29f4179b7433b7"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "2c98d35f5820a82a1876dcda059100d779a741fdf01753d47c113b0d8c1598b6"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.60.0+0/nghttp2.v1.60.0.i686-linux-musl.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "f5daf63baf1b51258d29e1a12e70a712ac4a755d"
os = "windows"

    [[nghttp2.download]]
    sha256 = "e87208cb22404cdf81edae33f85f6de327c73c1b4c4cf53a07295900f0340bea"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.60.0+0/nghttp2.v1.60.0.i686-w64-mingw32.tar.gz"
[[nghttp2]]
arch = "powerpc64le"
git-tree-sha1 = "9ccc546ad6010d1015240450be2a5a5282b9ac0e"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "61d65467c97c2ab883f370a4026d886c702c4667057a6a3c15b568b53e476a80"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.60.0+0/nghttp2.v1.60.0.powerpc64le-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "b0d2a4df06123535ab24bf85984410e3ae1ca3f8"
os = "macos"

    [[nghttp2.download]]
    sha256 = "2f62b00b9a3422947f6751ea3a47c548d5b49cb9ffe0fb33ff48f631f502902f"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.60.0+0/nghttp2.v1.60.0.x86_64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "dc8374f7981a08526c993d40d2f7bb30731fc15c"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "a87cf103995f73ebf5202b2afbfe5e41edc39b14beee8be916e3c210e14935aa"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.60.0+0/nghttp2.v1.60.0.x86_64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "a44b9953751a3a3f74fa5605ff8974df9200ab25"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[nghttp2.download]]
    sha256 = "53126f3908f95cdef22203881875d87554c074f3b8b5e4379fab4210604032a4"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.60.0+0/nghttp2.v1.60.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "aa1bba52763356ae5ea63d587b00d4c1cc76dcbe"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "990ea0c77933c8368d6a1bb55bef6b7e61f0f508f06395cab678622267b4a324"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.60.0+0/nghttp2.v1.60.0.x86_64-linux-musl.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "0ff37ff2c8661ed5e11514500ee50a59edc318a5"
os = "freebsd"

    [[nghttp2.download]]
    sha256 = "1be3d839c093c32a1bd4dde7b17c4fade1a70ab0972cdc66ae15542149c20504"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.60.0+0/nghttp2.v1.60.0.x86_64-unknown-freebsd.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "e493d53edabab4380724cbc9dd7e7f57de2333c9"
os = "windows"

    [[nghttp2.download]]
    sha256 = "2101b206f5c5924139707a3ed65b351c884ef6ce0d75a5616408af9114136324"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.60.0+0/nghttp2.v1.60.0.x86_64-w64-mingw32.tar.gz"
