[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "a07885f8fa5c2a0724bfa91c4a35285a70bbc87e"
os = "macos"

    [[nghttp2.download]]
    sha256 = "157ecb4429d54f57073174fc4f1dcdd1a0abd51aeb2ca0d3367f1345f59bca9e"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.67.0+0/nghttp2.v1.67.0.aarch64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "0d82f9eb69e5de720d0a4b82530317fd22a4bde3"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "b22531f05e4b79ec0c6fbec75153b72a85ea517b57201a98e7832286353a65a8"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.67.0+0/nghttp2.v1.67.0.aarch64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "bdffd37020a140b5b58b884ddc68c3ac58704937"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "a6bc2f05633878282fac7e6ed2b169072d44321a6c9a741198d04104708e2d76"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.67.0+0/nghttp2.v1.67.0.aarch64-linux-musl.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "ea21822d88038458aff41a54b195985861da3d18"
os = "freebsd"

    [[nghttp2.download]]
    sha256 = "5e3d228cb3975e2117c65c1f33120473095a81b381f024ae6dbe81e788529c61"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.67.0+0/nghttp2.v1.67.0.aarch64-unknown-freebsd.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "18705c8dc34f19f5d5a08b95188d413881e7f856"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "26da835bdc980177286e29f91a2e5741b6beb288c8bfcec0a458d72802fcd46f"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.67.0+0/nghttp2.v1.67.0.armv6l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1c8bc6f7450d9d11cff5e41e0eee3f47ced7f29d"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "9edcc97b0afdde520f3fe30b9033e7e6bd336599ac7399a67b81b7a72d5e6576"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.67.0+0/nghttp2.v1.67.0.armv6l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a8b6dc42e9250d2c242a237cede9ced4ff862509"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "bcafa98a5fe7c51484e5bd7a0b246f91c7a81159b49a31654b462629747422a7"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.67.0+0/nghttp2.v1.67.0.armv7l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "13a2ba2f5fba06d249c14414a3b9ca36d66b5480"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "9f3b7f0468b05144e076c9ee3d360768c3bf189e7eed8e976656c7144e6323e6"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.67.0+0/nghttp2.v1.67.0.armv7l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "a7ca9d479753a3e269c1263e20c814af1a6088f3"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "702d6f02053bcd0bc5cef11173174c94b6873ae2179eebaf80050b3344e69bc8"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.67.0+0/nghttp2.v1.67.0.i686-linux-gnu.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "9556748aa2ab1091d9f4393c69451fa91b585f0c"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "1e89b04aaeaafda91800af3a6c52697323c18ced944db74fce93b05dfbd3c5ad"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.67.0+0/nghttp2.v1.67.0.i686-linux-musl.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "57b60d296adac8df6ff57b585322717e4e98ca80"
os = "windows"

    [[nghttp2.download]]
    sha256 = "c6ffcaa7948295202b6548c9cd613dc84deb05bf0fcd7beaf15dee8f5ce491f6"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.67.0+0/nghttp2.v1.67.0.i686-w64-mingw32.tar.gz"
[[nghttp2]]
arch = "powerpc64le"
git-tree-sha1 = "e036c04a743f7e31982f51b9f150af7203641678"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "ec2d48a4146136de6582b750df8fb26a2c3a8e5467090ffdc36f18d0f0d9e876"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.67.0+0/nghttp2.v1.67.0.powerpc64le-linux-gnu.tar.gz"
[[nghttp2]]
arch = "riscv64"
git-tree-sha1 = "8bb52f6f194fca3779fe5eee300fc29f4c118a71"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "34ce3abaab6ed69aa35b1b32867c986676408a0f4f079b03ed6e7860f3730e64"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.67.0+0/nghttp2.v1.67.0.riscv64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "f2ea017f37c69ddf020e5a49bc628e9198f43c9a"
os = "macos"

    [[nghttp2.download]]
    sha256 = "27cd05b6b0e4ec67c0212d283b7d5d069f6906ba1d89c1b0fcddf9fd94e46086"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.67.0+0/nghttp2.v1.67.0.x86_64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "e7a587ee392bcfcfda783105107461ba8d085b54"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "5c400ed9f4a32062c589bde0bc08a0469f303489a40250ee6c844a19158d5f5d"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.67.0+0/nghttp2.v1.67.0.x86_64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "165c743ecd7f21ef86b4729bc2dbf82a3d57a9dd"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[nghttp2.download]]
    sha256 = "a19d50c071bf9fa9589673183c7efbee113b119221d199e99757e2b129adc048"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.67.0+0/nghttp2.v1.67.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "bfa587172163f0856350e955e477ad51f5180095"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "3d54c646d589802e80506af550fd1e6c2eb33e5382b50354a405a2314754bd70"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.67.0+0/nghttp2.v1.67.0.x86_64-linux-musl.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "6971a2f997916fc96cfbac74e3ae9a98822041e8"
os = "freebsd"

    [[nghttp2.download]]
    sha256 = "5dd194c9c48ce54488ba88768a3246015d89e18f8510d3790e2ba55b63b82115"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.67.0+0/nghttp2.v1.67.0.x86_64-unknown-freebsd.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "88d68d195200654eac0ae98251869147a6b9d8e8"
os = "windows"

    [[nghttp2.download]]
    sha256 = "f5010d9825e54e14a66b2ecadb98c0fd4ea1341820a284f99597a33863407ad8"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.67.0+0/nghttp2.v1.67.0.x86_64-w64-mingw32.tar.gz"
