[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "4fdbe0416720e1e2a2db01ca42a8c69075ccd335"
os = "macos"

    [[nghttp2.download]]
    sha256 = "e5e3c9c7874b0d3a741cde34ff83b40f830d7e5e89f48e0d71f2eb0c1a6d8f36"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.58.0+0/nghttp2.v1.58.0.aarch64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "558bceff6d26fcee108f371c0813080a1efccd88"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "c536726a96f9c722b1fb44ad3400efd7e11ad5792256a526cebabf719d2e6323"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.58.0+0/nghttp2.v1.58.0.aarch64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "82c23707a394e615533109c5b05fa82b541ebc8d"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "b59d4c3982f30b2c4f4263a145cd6c5c88f65f7646358bc8e952366b1e6408d8"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.58.0+0/nghttp2.v1.58.0.aarch64-linux-musl.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "46c22701cfbf0ee65f80f94efc86e25df08f8512"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "7bc4742622518d51a209739326d179014498204f3615b1e5a805346d096630cd"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.58.0+0/nghttp2.v1.58.0.armv6l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "026495a365d6971a4e1a12fc058d083bf93932ef"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "eb92c19f04144163aa7d71783767dc6275fa887369eb70b469bd3fdc12d0c5cb"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.58.0+0/nghttp2.v1.58.0.armv6l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6b95992a0525a830a3b9c743fcf191d9df3a6b7b"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "98070d0d766083eb576316ab252927759170038adf18d75ea121164a31fd48ab"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.58.0+0/nghttp2.v1.58.0.armv7l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1742813941a185f1decf5d766de755b51e3ef87e"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "f4c5bb5fecc77cd89a71cb08ed11b6f6d46ed123add1db8379772b2f736b7b24"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.58.0+0/nghttp2.v1.58.0.armv7l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "fa7f1d0c7d3f58004ebb566ee38258a060340fbe"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "ce564ce88cea096c7d6d4c86585048612837d6a08b49e7b6b1f8195dd9713228"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.58.0+0/nghttp2.v1.58.0.i686-linux-gnu.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "b813e1d12947351035604e341c1e9dcbf4140a21"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "d9ed1a338dc0cc09ea1367382d45856042646594540b98e8e0fd4a94fab51b8e"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.58.0+0/nghttp2.v1.58.0.i686-linux-musl.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "86b1609fb469634e00af8b24e3c052efbff9cbdf"
os = "windows"

    [[nghttp2.download]]
    sha256 = "3c79e8405481259c645f5fc9e0bc0642fa48612ae13497136b1e91cb177db533"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.58.0+0/nghttp2.v1.58.0.i686-w64-mingw32.tar.gz"
[[nghttp2]]
arch = "powerpc64le"
git-tree-sha1 = "dca871d96717adbdb8da8950dfcf77ca05e5d006"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "7b111f9faed45592a2b4eee2f0b045510993cae0cd98d8ba4c872b9ed7d7083e"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.58.0+0/nghttp2.v1.58.0.powerpc64le-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "8907e9071c82d84ae4e347663655eff58ac4de7d"
os = "macos"

    [[nghttp2.download]]
    sha256 = "3fc2314e27deda176d275cc508f0fd6a0e6f720d4553b1b97abd2d1a02547ce4"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.58.0+0/nghttp2.v1.58.0.x86_64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "e6928a47e1a0453e2e5ee81142ef701396a8b778"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "a73df8feca689e6f78a652ec0a11a870ad90a1738a2e1105b3c1b8f3fe8436f3"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.58.0+0/nghttp2.v1.58.0.x86_64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "becd6c76940103b86a6c41f8efe070302b2130e6"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[nghttp2.download]]
    sha256 = "17452f26c17abe2d7bcbff123737e502fce893473c7a0b8fd3b009098ffea583"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.58.0+0/nghttp2.v1.58.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "26845721a2de522cbeaab82f78f8c4789bbfdbea"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "87cd7ca9c779184a1b3423267f1adf12e9f1831b4cc6a1bdb7fc3c465998ea3a"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.58.0+0/nghttp2.v1.58.0.x86_64-linux-musl.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "7bb4fa72a36b9b4acf1d6c513b79fa765217ef50"
os = "freebsd"

    [[nghttp2.download]]
    sha256 = "63ec24c220d318d220e94e00d9ec4b0414cf8eed07ce9ee10b41bc0686a4abbb"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.58.0+0/nghttp2.v1.58.0.x86_64-unknown-freebsd.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "6757fdc3f88e6562265098aca9e541b252687874"
os = "windows"

    [[nghttp2.download]]
    sha256 = "184c9bc2845c292fb10403154c513c8ef6b598e3f025fb7ff891fda885731cdd"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.58.0+0/nghttp2.v1.58.0.x86_64-w64-mingw32.tar.gz"
