[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "60f866865cab8a19dabcd01271d774f32e4dc814"
os = "macos"

    [[nghttp2.download]]
    sha256 = "93beea3ce5ed5099c068b314f1b40d156025f613b64a4a6de17d6037d1abd623"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+3/nghttp2.v1.41.0.aarch64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "b058a3cbacc4b864f5924c50c9b0f62f3af43b77"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "315a295e58598b166835b74560b662053e652c0583ef519d852aa23b9c5cc9bd"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+3/nghttp2.v1.41.0.aarch64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "b063b091535e72ae82fd793942deb745de4f8a78"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "91a78cfc1e93170faf7f11f8e9b47da3fbc576b0b5768e14711817e421b1f150"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+3/nghttp2.v1.41.0.aarch64-linux-musl.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "95016972362a480b9587cdc41b3caa384c44aed7"
os = "freebsd"

    [[nghttp2.download]]
    sha256 = "21db512779f5c85367d244e33fdd0edcce5650361c9220286a469278df7465f6"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+3/nghttp2.v1.41.0.aarch64-unknown-freebsd.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "269a3e81f9bb741dbb7102d5e658d8de2406275c"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "a8e9c63734c4e292c10573ccd999866b5c02977c68ccfe02dad981348acbe90f"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+3/nghttp2.v1.41.0.armv6l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "453743c8356eab07c86acdf89e68c8271c35c3d0"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "580a2b7005106b39dfa5a87a89ef6ba2bbc8e0b2bf36836547402a35e247484a"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+3/nghttp2.v1.41.0.armv6l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "32207465d11328a78589cf636da4571ea8d1b328"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "968bdc80d03f37166945d9ff620bcdb73f02b4b238f3c943a2bc0a9549c084d7"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+3/nghttp2.v1.41.0.armv7l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5e41b1a633ad52d36bd9004b56f40fd5d7997f9d"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "7787dbf8ea7b2ac37a8d0c77b7e80451b6e6f581eeb0229f553abf3fc0bf14f8"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+3/nghttp2.v1.41.0.armv7l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "3d329cea0690eae62889936f82edcd934a797ce1"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "043b41ee4c0673c3f50df8e2f75f8b0e0bcdd27a50237e4150fea74a9fe33272"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+3/nghttp2.v1.41.0.i686-linux-gnu.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "eef5ccad31bfdff8513b02a5f01f17dc6af126a1"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "1b0b315f855119acbec70bbbb3ec5e973d71c7295d0c64940e71e6d58f273299"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+3/nghttp2.v1.41.0.i686-linux-musl.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "292fdb0694f31cecb7c34110e36c58347200b271"
os = "windows"

    [[nghttp2.download]]
    sha256 = "bee5a1d8766ff7b3dab9eb2b74e7047fdcf075e146e6ad4e00ffeb4ca8623139"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+3/nghttp2.v1.41.0.i686-w64-mingw32.tar.gz"
[[nghttp2]]
arch = "powerpc64le"
git-tree-sha1 = "86edf7c6d3883eb400c6ca5e56758fc1911d014a"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "11ea9e567190ac219555659b734c9e1b29f00ceb8525baa74ac26446b0faecf4"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+3/nghttp2.v1.41.0.powerpc64le-linux-gnu.tar.gz"
[[nghttp2]]
arch = "riscv64"
git-tree-sha1 = "c5a8cca922ef736f6c6a29bfcaf539aa6503f1a9"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "a4fee59c9e0aa938c9c4e8dc8c466856de943e03e78e1838719e792e63e220e7"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+3/nghttp2.v1.41.0.riscv64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "6421d831e7b36a41d4aea311c55ab0c98b7245be"
os = "macos"

    [[nghttp2.download]]
    sha256 = "238cf6e12cb5939283b3b2317c2bdbcff93b77597f5ea067e91bbbb6dd006fcd"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+3/nghttp2.v1.41.0.x86_64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "f49c0cf1cce3e83177e52ff6f7860c628725a024"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "17517c95ac8f78bd54440aa8da96f42e0d3a5ce8cf449896e0e4b211a72b4c9b"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+3/nghttp2.v1.41.0.x86_64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "f48f02261cd98fc0c2680b3d424462979adb0b62"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[nghttp2.download]]
    sha256 = "49314508a81e5f99447c22224b8ecdbdc86e78b35af7b4fc2cb623acfbc2adfa"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+3/nghttp2.v1.41.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "de0ce500bc53cf5f4ebb24d9a802c0c30a2cb5fa"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "55337967dc47c5739df26badb7ec40d0422d306937c829dbd500fa896b925d8f"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+3/nghttp2.v1.41.0.x86_64-linux-musl.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "fd109856af891841d7f3a35b7fa5a71bbfba1269"
os = "freebsd"

    [[nghttp2.download]]
    sha256 = "baab9a6453f4bd8b5e750a4cdcd5b4cfc0ca87b1d2bbc63c9214d3952d3e8a8a"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+3/nghttp2.v1.41.0.x86_64-unknown-freebsd.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "260ef09192b2eadedb91df713e8aaba2b9bd040d"
os = "windows"

    [[nghttp2.download]]
    sha256 = "e89d5d618cbdc696644c2b598005b1c3d56758eb60086e336f19e264926bb6e6"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.41.0+3/nghttp2.v1.41.0.x86_64-w64-mingw32.tar.gz"
