[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "87efeaf100df9fd60b8624d505c350aa92db1171"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "ad77cc8d02d2db702f1aef2f50dca08be90df8c93783a95dc5bd8f6af6f1b1e3"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.40.0+2/nghttp2.v1.40.0.aarch64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "dcc758f6c79c710ca0188ccd20d45faedddc090a"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "7bf6815355cca1b31067a581ed2cd3a4af00cdaa674fc3c703585404bd6b59e5"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.40.0+2/nghttp2.v1.40.0.aarch64-linux-musl.tar.gz"
[[nghttp2]]
arch = "armv7l"
git-tree-sha1 = "3f92ccc5bd2e31611e4d6b6637749441daee5047"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "ccacc982d9b96ed3f5529ed878a65f05f1d0eefa4955bb8eaf36e1e804fb0107"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.40.0+2/nghttp2.v1.40.0.armv7l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
git-tree-sha1 = "ccfae7e95b3e6fd78f9455c9eeb38350dda3ddbf"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "8097a904c559c5bff4a48bcb14963c40c796cdc6522f94c6df4491fc95bd4583"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.40.0+2/nghttp2.v1.40.0.armv7l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "d11e4b29a461cf5a24044dc4c7f82b4f37785c0b"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "e30d08a914cb669b74ed2c156f0b1ff8cf8c53624f5c9e595a17f3f1607d07f8"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.40.0+2/nghttp2.v1.40.0.i686-linux-gnu.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "8c58c1f62abed21620b67f4569efd60d7391ff7b"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "6691861363e9833586e0304319982273338c2c627478dd1a9df7cae6ab2ad5f6"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.40.0+2/nghttp2.v1.40.0.i686-linux-musl.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "13c310a4a73697fdd9cd99d0dea663f859daf869"
os = "windows"

    [[nghttp2.download]]
    sha256 = "178ee110fcb5ad687ca6f69066110462d4df9dbff5706d00abcc9ec358e82bb6"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.40.0+2/nghttp2.v1.40.0.i686-w64-mingw32.tar.gz"
[[nghttp2]]
arch = "powerpc64le"
git-tree-sha1 = "66f4c7e5a2db93bb7aeb79070867b9a700dfa0b3"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "32e1b01b89ab2bd94c9487719d11995048bac389120e3eef37bf1a3f75732e4a"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.40.0+2/nghttp2.v1.40.0.powerpc64le-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "9a035d13c19b8cb29d80e3d3c3b4f18fd61bf03d"
os = "macos"

    [[nghttp2.download]]
    sha256 = "82347ed6fa872dbcdeaeb1c0d56ab6222b467f4526feeaa9575d0be46eb1b120"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.40.0+2/nghttp2.v1.40.0.x86_64-apple-darwin14.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "866d2adc53c818f1fedc9d9bfd0d03126572f5cd"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "3aa3cdee9aea6165186635a9fb21ff1ff9064ef24b9f7adfdc5ff39b86f4face"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.40.0+2/nghttp2.v1.40.0.x86_64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "083cae0b511a4a69235c8e2372e5b93f55dab23c"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "33b7bb36aa8b751d3956ca811efe8625b9c6119aab7c41b917e3a867ccd3ed09"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.40.0+2/nghttp2.v1.40.0.x86_64-linux-musl.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "6a1e427ba829ac84bcd467229e59468615ca1123"
os = "freebsd"

    [[nghttp2.download]]
    sha256 = "9ce1db55681e4a22b9de1bac862382aca3b188b6e83b08a2d0196f656cb5971b"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.40.0+2/nghttp2.v1.40.0.x86_64-unknown-freebsd11.1.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "bdeeb133a67a52079b5206e7f9f3a7cbdf357969"
os = "windows"

    [[nghttp2.download]]
    sha256 = "0068ad314e83ffbd61f6546af95fddb844e1dea4b8e7dffe517ab438d698d7d6"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.40.0+2/nghttp2.v1.40.0.x86_64-w64-mingw32.tar.gz"
