[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "5f40cf808bc4f24d03471a312df8f1772cc22aef"
os = "macos"

    [[nghttp2.download]]
    sha256 = "ee24e2b673bc9483cd0cb07af297e6ba07fd39f870e618db46a44b680b5896e0"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.59.0+0/nghttp2.v1.59.0.aarch64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "c9f7a2dcdb580c5c14c04e114eb9aeab50d62394"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "251b6f44e45d6ab0ec7bacd5e3b501d30d2ff8505aa64c8141485a7a44728873"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.59.0+0/nghttp2.v1.59.0.aarch64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "8496b407d9cef2e152a8a471348e07e313c1251f"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "c3fccc2e37c6d5cddd21073b27bf57771f7f87418fa9b91fbb0a73d32d135b65"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.59.0+0/nghttp2.v1.59.0.aarch64-linux-musl.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ebce428d500ce863b9a40d0267d2f2126021a916"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "b1ce0b3d246dd43cee73b6ff13908860f4b8620d8cf53d56b2bf3cc14bd8d710"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.59.0+0/nghttp2.v1.59.0.armv6l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "014322e5b83eaa6bbb6e4a6d07377186c94821b4"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "9ff336f5110a0967d8c32ea9a76515af9c687c2f9979b08de1f249479bed8685"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.59.0+0/nghttp2.v1.59.0.armv6l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4ddd984033942a2a29b2323605ff57aaf99c4ddd"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "d6b01ffdc10f4e2eb9670c89a6461d6a15e3c0790346e78802e1028e475472ed"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.59.0+0/nghttp2.v1.59.0.armv7l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "947a65f6c750b3bcb491cfce8b4790331a2314a5"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "9c596ee558d82dd971976d224ee9ca3486fae8f74aa1d159aeff3b688710e455"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.59.0+0/nghttp2.v1.59.0.armv7l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "bbb8737b24ce2a94303ed27a5126bb6d5e2c397f"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "862d6013c0ae6dd60adc8f8fa47908bade40341df5d49a48c3b7294c778d769d"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.59.0+0/nghttp2.v1.59.0.i686-linux-gnu.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "90c298571441d97f8e6f064204ead282f30f3ee8"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "b2788037ed9d8778ba3003726c86a93a3fb94b3ee5a6c56bf677eafb0ef8ab7f"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.59.0+0/nghttp2.v1.59.0.i686-linux-musl.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "64c448b16f68fe68b0a23a9c4ecb0f0e371919d4"
os = "windows"

    [[nghttp2.download]]
    sha256 = "fd6808891bf978589fc94de3cd91ec85c6cd47e26ea85c55f3162c9883814f13"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.59.0+0/nghttp2.v1.59.0.i686-w64-mingw32.tar.gz"
[[nghttp2]]
arch = "powerpc64le"
git-tree-sha1 = "7fdaaa984559a5d59aec20650165fe8dfa90f57c"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "543c5fe4afc9f2b873c27d389c505a155173d4eaec1fe2f6817b9257bbb1cb6e"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.59.0+0/nghttp2.v1.59.0.powerpc64le-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "6f19d528e7710315ec0f6fd3e84c4e70ba56c64b"
os = "macos"

    [[nghttp2.download]]
    sha256 = "df3ec8cfc56042162cdbdf0e9910d476a295c6bad146724ffc7856fa177b3ce2"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.59.0+0/nghttp2.v1.59.0.x86_64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "5ec786e322fea14df484968036e862b6eef4f377"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "b8f0b947cc5b7d40dcc83de77a2ad4b64342edddf8f4ea5dcf7962e1c272c61e"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.59.0+0/nghttp2.v1.59.0.x86_64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "17b1a3ad8167612d1732a6fa743ef20175b7d7ce"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[nghttp2.download]]
    sha256 = "1168753f795f02515f87a85022fec9bfc02f6dca6342e1f1759748cd2c387d02"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.59.0+0/nghttp2.v1.59.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "6048acd9a1beb2e92faa65816cd9270b3ef535c8"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "9feceb74894d0f7fcc21f76db4f898a6f7c3a3ea4fd3fe6ee0462a455db951ce"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.59.0+0/nghttp2.v1.59.0.x86_64-linux-musl.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "61405173005aa6b300c77ba3cbe899c3f6ea74d6"
os = "freebsd"

    [[nghttp2.download]]
    sha256 = "4f7d0afadd7e24fc3a2407212495b810ff019a48486c7ac25a007d8074115fa4"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.59.0+0/nghttp2.v1.59.0.x86_64-unknown-freebsd.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "7cc71a57b28306bd0672eb03fdc31022a4f24b31"
os = "windows"

    [[nghttp2.download]]
    sha256 = "97f269985d78916c473dc5ed8b6e954dfa251a48f2364ff17acf88ce206a2bbe"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.59.0+0/nghttp2.v1.59.0.x86_64-w64-mingw32.tar.gz"
