[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "cc208ded24eee06ebf459def013e820f0e85fa12"
os = "macos"

    [[nghttp2.download]]
    sha256 = "53c5d48fc72d9321af8ee19d0d22a96fe85cc3ec9db2347de969828499d68fe7"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.0+0/nghttp2.v1.62.0.aarch64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "9b5817c52cf536423d2c3891973763ac9ef67714"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "cf1f9399908754aabab0f6f0d373bb66ed586a798fd9e82d808fe2272bbb25af"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.0+0/nghttp2.v1.62.0.aarch64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "aarch64"
git-tree-sha1 = "29e7c60b2e2a31bd0ddd255501938e13eae70ca1"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "89c1b5e972b7258bd8e25be0f1aa62ed82cca5eb80201113e172fb7ee03cca89"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.0+0/nghttp2.v1.62.0.aarch64-linux-musl.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e7cf0d4f52a9acf644018f5e28ce3df7d6fabacd"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "419ca72c3d70f98c28384c75ae6ae3b364724300d6d9bbd35dc490059a858410"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.0+0/nghttp2.v1.62.0.armv6l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "aef3b26c558dcf8671c9d3239ee41640cd3c1752"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "d157b2c268d7cfe92ac1377bf3a30eb0234413bcee8301a85758cc81b739c4d7"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.0+0/nghttp2.v1.62.0.armv6l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "289b3094797d1f930c9b2c31c03b71f00670fdb1"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "ec18fbf15cfe87684c90564df1259358b7f799ab5080adab2d5efeb3740692c5"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.0+0/nghttp2.v1.62.0.armv7l-linux-gnueabihf.tar.gz"
[[nghttp2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "47741d37139e2402b72e7e77c5d46598962fe0c0"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "c07d68ecfecea8cba6c1a2a0a12be6dd96388e0335a4959ba87847e1ddcd8d77"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.0+0/nghttp2.v1.62.0.armv7l-linux-musleabihf.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "f1d6c3644f511c3bb4a38d5ef3ec0d9d8b3f47f8"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "9ff1a18605a4ff2ae19bf89dc2ec325592fae5c96d5fd7639742ee6d321fb7e5"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.0+0/nghttp2.v1.62.0.i686-linux-gnu.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "43c1abfaa24b135ded13a644c0ba391a64fac2a2"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "19af6c613547d31b7bf20e20ee243d3254eae02d32b6b55af5097afad75a095a"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.0+0/nghttp2.v1.62.0.i686-linux-musl.tar.gz"
[[nghttp2]]
arch = "i686"
git-tree-sha1 = "8ca0d471008d85ff479f0ddaa8cebb5cacca4be7"
os = "windows"

    [[nghttp2.download]]
    sha256 = "73f67049ac167415f44e3e0a8fd7835cd0503bd7854e6cd09c16366940a8e0a8"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.0+0/nghttp2.v1.62.0.i686-w64-mingw32.tar.gz"
[[nghttp2]]
arch = "powerpc64le"
git-tree-sha1 = "0bb81b803ce4b38d5ef4e25222ef08cce8ed284e"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "c251c1ea6dcc3ddbb3bae715697b28d74cbf5ad25ac6f1ec3d2e8bb7d50093f9"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.0+0/nghttp2.v1.62.0.powerpc64le-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "ff9e8d2fac29f75dd102601f44da3d71c4ca57f8"
os = "macos"

    [[nghttp2.download]]
    sha256 = "cbc26789af61dae51175cb26e9b55c5381393c095f2cfef24841635ca670f9e7"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.0+0/nghttp2.v1.62.0.x86_64-apple-darwin.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "a48d2c0ac018d76f72e0bb55eb07426250a860ef"
libc = "glibc"
os = "linux"

    [[nghttp2.download]]
    sha256 = "3b283e9db4f562ac2b5f66dd1415cfff80a13db324b97636300ff58356fcf30b"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.0+0/nghttp2.v1.62.0.x86_64-linux-gnu.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "21bfd4bf6c7fc332965076a9d851361f4efc8518"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[nghttp2.download]]
    sha256 = "7ef9765c08bab4c27789fee458199570dea4388cad1f396ec48810f91a049a88"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.0+0/nghttp2.v1.62.0.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "87353a09b5cbccb6ec726f319f8e03cc0e59f951"
libc = "musl"
os = "linux"

    [[nghttp2.download]]
    sha256 = "f037d2727102b8abfb21e60a8beb73581f734ee916c4d5da2be654ea1ceabdc7"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.0+0/nghttp2.v1.62.0.x86_64-linux-musl.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "9f729556b2744e2761f6c92221f4d35f81f2a739"
os = "freebsd"

    [[nghttp2.download]]
    sha256 = "71bef0344113c1a30b05b982bf8efc32030ce6b655aa9c345b1cd88942b4b091"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.0+0/nghttp2.v1.62.0.x86_64-unknown-freebsd.tar.gz"
[[nghttp2]]
arch = "x86_64"
git-tree-sha1 = "0e61da703717f9f615bd526b6d513a10939febe2"
os = "windows"

    [[nghttp2.download]]
    sha256 = "77c484e1143e362ff80c2de3169d3f9e655adbf8d77bb5e315c477c5e4e3e25f"
    url = "https://github.com/JuliaBinaryWrappers/nghttp2_jll.jl/releases/download/nghttp2-v1.62.0+0/nghttp2.v1.62.0.x86_64-w64-mingw32.tar.gz"
